cs2go/forums/forms.py
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import InputRequired, DataRequired


class QuestionForm(FlaskForm):
    subject = StringField('Subject', validators=[InputRequired()])
    description = CKEditorField('Body', validators=[DataRequired()])
    submit = SubmitField('Submit')


class ReplyForm(FlaskForm):
    questionId = HiddenField('Question ID')
    description = CKEditorField('Body', validators=[DataRequired()])
    submit = SubmitField('Submit')

cs2go/forums/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from cs2go.models import Post
from cs2go.forums.forms import QuestionForm
from cs2go.forums.forms import ReplyForm
from cs2go.models import User, Comment

forums_blueprint = Blueprint('forums',
                             __name__,
                             template_folder='templates/forums')


# CRUD FOR THE QUESTION
@forums_blueprint.route('/questions', methods=['GET', 'POST'])
def questions():
    if session.get('email'):
        # get the logged in user by session.get('email')
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get all the question from the Post table
            posts = Post.objects()
        else:
            return redirect(url_for('students.profile'))
        return render_template('questions.html', posts=posts, user=user)
    else:
        return redirect(url_for('login'))


@forums_blueprint.route('/questions/add', methods=['GET', 'POST'])
def create_question():
    # get the logged in user by session.get('email')
    if session.get('email'):
        form = QuestionForm(request.form)
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            if request.method == 'POST' and form.validate():
                # First save the Question
                post = Post()
                post.subject = form.subject.data
                post.description = form.description.data
                post.author = user.name + ' ' + user.surname
                # After saving question get the id of the question
                post.save()
                # Push the id of the question
                user.posts.append(post.id)
                user.save()
                # redirect the user in the questions routes
                return redirect(url_for('forums.questions'))
        else:
            return redirect(url_for('students.profile'))
        return render_template('add-question.html', form=form, user=user)
    else:
        return redirect(url_for('login'))


@forums_blueprint.route('/questions/details/<question_id>', methods=['GET', 'POST'])
def question_details(question_id):
    if session.get('email'):
        # get the logged in user by session.get('email')
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get the question by the question id from the database
            question = Post.objects(id=question_id).first()
            # Also populate all the replies to that question
            question_comments = Post.objects(comments__in=question.comments)
            comments = []
            for q in question_comments:
                comments = q.comments
        else:
            return redirect(url_for('students.profile'))

        return render_template('question-details.html', question=question, comments=comments, user=user)
    else:
        return redirect(url_for('login'))


# CRUD FOR THE REPLY
@forums_blueprint.route('/questions/reply/<question_id>', methods=['GET', 'POST'])
def question_reply(question_id):
    if session.get('email'):
        # get the logged in user by session.get('email')

        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get the question by question id from the database
            question = Post.objects(id=question_id).first()
            form = ReplyForm(request.form)
            form.questionId.data = question.id
            if request.method == 'POST' and form.validate():
                comment = Comment()
                comment.author = user.name + ' ' + user.surname
                comment.description = form.description.data
                comment.post = question.id
                comment.save()
                question.comments.append(comment.id)
                question.save()
                return redirect('/forums/questions/details/' + str(form.questionId.data))
        else:
            return redirect(url_for('students.profile'))
        return render_template('question-reply.html', form=form, question=question, user=user)
    else:
        return redirect(url_for('login'))


@forums_blueprint.route('/reply/remove/<comment_id>', methods=['GET', 'POST'])
def remove_reply(comment_id):
    if session.get('email'):
        question_id = request.args.get('question_id')
        question = Post.objects(id=question_id).first()
        comment = Comment.objects(id=comment_id).first()
        # remove the comment from the database
        new_comments = list(filter(lambda x: x.id != comment.id, question.comments))
        question.comments = new_comments
        question.save()
        comment.delete()
        # also remove the comment from the question comment array
        return redirect(url_for('forums.question_details', question_id=question_id))
    else:
        return redirect(url_for('login'))


@forums_blueprint.route('/question/remove/<question_id>', methods=['GET', 'POST'])
def remove_question(question_id):
    if session.get('email'):
        user = User.objects().filter(email=session.get('email')).first()
        question = Post.objects(id=question_id).first()
        comments = Comment.objects(post=question.id)
        # remove the comment from the database
        new_user_posts = list(filter(lambda x: x.id != question.id, user.posts))
        user.posts = new_user_posts
        user.save()
        question.delete()
        comments.delete()
        # remove the comment from the question comment array
        return redirect(url_for('forums.questions'))
    else:
        return redirect(url_for('login'))

cs2go/forums/templates/forums/add-question.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>

            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li><a data-toggle="tooltip" title="View all files" href="{{ url_for('files.file_list') }}"><span
                            class="glyphicon glyphicon-file"></span></a></li>
                    <li><a data-toggle="tooltip" title="View students"
                           href="{{ url_for('students.student_list') }}"><span
                            class="glyphicon glyphicon-list" data-toggle="tooltip"
                            data-original-title="Users"></span></a></li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">{{ user.name }} {{ user.surname }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}">
                                <i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li><a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>
                                Files</a></li>
                            <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                out</a></li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method="post" action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        <div style="background-color: #D8BFD8;padding: 10px;border-radius: 5px">
            <a href="{{ url_for('forums.questions') }}">
                <span><i class="fa fa-long-arrow-left" aria-hidden="true" style="font-size: 18px;"></i></span>
                <span style="margin-left: 5px">Back to discussion form</span>
            </a>
        </div>
        <h3 style="margin: 24px 0">Teacher Discussion Forum</h3>
        <div>
            <h4 style="margin: 24px 0">Your new Questions</h4>
        </div>
        <form action="{{ url_for('forums.create_question') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-inline">
                <label>Subject:</label>
                {{ form.subject(class='form-control',style='width:100%',placeholder="Write a subject") }}
            </div>
            <div>
                <h4 style="margin-top: 40px">Your Question:</h4>
                {{ form.description(class='form-control') }}
            </div>
            {{ form.submit(class="btn btn-info",style="float: right; padding: 6px 16px; background-color: #D8BFD8; border:
        #D8BFD8; color: black; font-weight: bold; margin-top: 24px") }}
        </form>
    </div>

{% endblock %}

cs2go/forums/templates/forums/question-details.html
{% extends "base.html" %}


{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>

            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li><a data-toggle="tooltip" title="View all files" href="{{ url_for('files.file_list') }}"><span
                            class="glyphicon glyphicon-file"></span></a></li>
                    <li><a data-toggle="tooltip" title="View students"
                           href="{{ url_for('students.student_list') }}"><span
                            class="glyphicon glyphicon-list" data-toggle="tooltip"
                            data-original-title="Users"></span></a></li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">{{ user.name }} {{ user.surname }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li><a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>
                                Files</a></li>
                            <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                out</a></li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method="post" action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        <div style="background-color: #D8BFD8;padding: 10px;border-radius: 5px">
            <a href="{{ url_for('forums.questions') }}">
                <span><i class="fa fa-long-arrow-left" aria-hidden="true" style="font-size: 18px;"></i></span>
                <span style="margin-left: 5px">Back to discussion form</span>
            </a>
        </div>
        <h3 style="margin: 24px 0px">Teacher Discussion Forum</h3>
        <div>
            {% if question %}
                <h4 style="margin: 24px 0px">{{ question.subject }}</h4>
            {% endif %}
            <a href="/forums/questions/reply/{{ question.id }}" class="btn btn-info"
               style="float: right; margin-top: -52px; padding: 6px 20px; background-color: #D8BFD8; border-color: #D8BFD8; color: black; font-weight: bold">
                Reply
            </a>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading" style="background-color: #D8BFD8">
                {% if question %}
                    <h4 style="color: black">{{ question.subject }}</h4>
                    <p style="color: black">Asked
                        by {{ question.author }}, {{ question.created_at.strftime('%Y-%m-%d') }} </p>
                {% endif %}
            </div>
            <div class="panel-body">
                {% if question %}
                    {{ question.description | safe }}
                {% endif %}
            </div>
        </div>

        {% if comments %}
            <div class="comments" style="padding-left: 50px">
                {% for comment in comments %}
                    <div class="panel panel-primary">
                        <div class="panel-heading" style="background-color: #D8BFD8">
                            {% if question %}
                                <h4 style="color: black">Re : {{ question.subject }}</h4>
                                <p style="color: black">Answered
                                    by {{ comment.author }}, {{ comment.created_at.strftime('%Y-%m-%d') }} </p>
                            {% endif %}
                        </div>
                        <div class="panel-body">
                            {{ comment.description | safe }}
                        </div>
                        {#Here display the comment delete button#}
                        {% if user.user_type=='admin' %}
                            {# Display the schools #}
                            <div style="text-align: right;padding-bottom: 10px;padding-right: 10px">
                                <a href="{{ url_for('forums.remove_reply',comment_id=comment.id,question_id=[question.id]) }}"
                                   class="btn btn-danger">Delete</a>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock %}

cs2go/forums/templates/forums/questions.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>

            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li>
                        <a data-toggle="tooltip" title="View all files" href="{{ url_for('files.file_list') }}">
                            <span class="glyphicon glyphicon-file"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tooltip" title="View students" href="{{ url_for('students.student_list') }}">
                            <span class="glyphicon glyphicon-list" data-toggle="tooltip"
                                  data-original-title="Users"></span>
                        </a>
                    </li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            {{ user.name }} {{ user.surname }}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li>
                                <a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>Files</a>
                            </li>
                            <li>
                                <a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i>
                                    Log out
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method="post" action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        <div class="d-inline-flex">
            <h3>Teacher Discussion Forum</h3>
            <a href="{{ url_for('forums.create_question') }}" class="btn btn-info"
               style="margin: 28px 28px 16px 0px; background-color: #D8BFD8; border-color: #D8BFD8; color: black; font-weight: bold">
                Ask your Own
            </a>

            <table id="content" class="table table-hover table-responsive">
                <thead>
                <tr>
                    <th>Questions</th>
                    <th class="text-center">Replies</th>
                    <th>
                        <div style="text-align: right">Started By</div>
                    </th>
                    {% if user.user_type=='admin' %}
                        <th class="text-center">Action</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% if posts %}
                    {% for post in posts %}
                        {#Check the loop by index#}
                        {% if loop.index % 2 == 0 %}
                            <tr style="background-color: rgb(213,206,218)">
                                <td style="vertical-align: middle"><a
                                        href="/forums/questions/details/{{ post.id }}">{{ post.subject }}</a></td>
                                <td align="center" style="vertical-align: middle">{{ post.comments | count }}</td>
                                <td align="right" style="vertical-align: middle"><p>{{ post.author }}
                                    <br> {{ post.created_at.strftime('%Y-%m-%d') }}</p>
                                </td>
                                {% if user.user_type=='admin' %}
                                    <td>
                                        <div class="text-center">
                                            <a href="{{ url_for('forums.remove_question',question_id=post.id) }}"
                                               class="btn btn-danger">Delete</a>
                                        </div>
                                    </td>
                                {% endif %}
                            </tr>
                        {% else %}
                            <tr style="background-color: rgb(245,240,240)">
                                <td style="vertical-align: middle"><a
                                        href="/forums/questions/details/{{ post.id }}">{{ post.subject }}</a></td>
                                <td align="center" style="vertical-align: middle">{{ post.comments | count }}</td>
                                <td align="right" style="vertical-align: middle"><p>{{ post.author }}
                                    <br> {{ post.created_at.strftime('%Y-%m-%d') }}</p></td>
                                {% if user.user_type=='admin' %}
                                    <td>
                                        <div class="text-center">
                                            <a href="{{ url_for('forums.remove_question',question_id=post.id) }}"
                                               class="btn btn-danger">Delete</a>
                                        </div>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <div id="pagination"></div>
        </div>
    </div>
{% endblock %}