cs2go/students/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
import bcrypt

from cs2go.students.forms import StudentForm, EditForm, StudentPersonalQs, StudentCSQs
from cs2go.models import User, School, Module1, Module2, Module3, Assignment, PersonalQuestions, CSQs, BebrasQuiz1, BebrasQuiz2
from bson import ObjectId
import datetime

students_blueprint = Blueprint('students',
                               __name__,
                               template_folder='templates/students')


@students_blueprint.route('/create', methods=['GET', 'POST'])
def create():
    form = StudentForm(request.form)
    # get all the schools from the schools table
    school_list = [(str(row.id), row.name) for row in School.objects()]
    form.school.choices = school_list

    if request.method == 'POST' and form.validate():
        # check if a user exist with the given email or not
        existing_user = User.objects().filter(email=form.email.data).first()
        if existing_user is None:
            # have to hash password
            #get the school id here.
            hash_password = bcrypt.hashpw(form.password.data.encode('utf-8'), bcrypt.gensalt())
            # check if the school is listed or not
            school_id = form.school.data
            user = User()
            # create instance of User model and assign form data to it 
            user.user_type = 'student'
            user.name = form.name.data
            user.surname = form.surname.data
            user.email = form.email.data
            user.password = hash_password
            user.approved = False
            user.login_counter = 1
            user.login_array = [datetime.datetime.now()]
            user.school = ObjectId(school_id)
            user.save()
            session['email'] = user.email
            return redirect(url_for('students.PersonalQuestion'))
        else:
            flash('User with this email already exist')
            return redirect(url_for('students.create'))

    return render_template('student-create.html', form=form)


# route to get the form information from the personal quiz
@students_blueprint.route('/PersonalQs', methods=['GET', 'POST'])
def PersonalQuestion():
    form = StudentPersonalQs(request.form)
    if request.method == 'POST' and form.validate():
        personalqs = PersonalQuestions()
        personalqs.userid = session['email']
        personalqs.gender = form.Gender.data
        personalqs.age = form.Age.data
        personalqs.year = form.Year.data
        personalqs.englishspeaker = form.NativeEnglishSpeaker.data
        personalqs.mornornight = form.MorningOrNight.data
        personalqs.personalsmartphone = form.OwnSmartPhone.data
        personalqs.phoneaccess = form.HaveSphoneAccess.data
        personalqs.phonehours = form.PhoneHours.data
        personalqs.phoneactivity = form.PhoneActivity.data
        personalqs.personalcomputer = form.OwnPersonalComputer.data
        personalqs.nocomputer = form.HaveComputerAccess.data
        personalqs.computerhours = form.ComputerHours.data
        personalqs.computeractivity = form.ComputerActivity.data
        personalqs.personaltablet = form.OwnTablet.data
        personalqs.tablethours = form.TabletHours.data
        personalqs.tabletactivity = form.TabletActivity.data
        personalqs.programmingexperience = form.ProgrammingExperience.data
        personalqs.programmingexperiencetime = form.ProgrammingExperienceTime.data
        personalqs.programminglanguages = form.ProgrammingLanguages.data
        personalqs.programoften = form.ProgramOften.data
        personalqs.programminglevel = form.PersonalProgrammingProficiency.data
        personalqs.weborappdev = form.DoneWebOrAppDev.data
        personalqs.technologies = form.KnownTechnologies.data
        personalqs.programmingsite = form.ProgrammingSites.data
        personalqs.jclevel = form.JuniorCertLevel.data
        personalqs.parentoccupation = form.ITParentOccupation.data
        personalqs.save()
        return redirect(url_for('students.CSQuestion'))

    elif request.method == 'POST' and form.validate() == False:
        if form.errors:
            errors = form.errors
            for i in errors:
                flash(i)
         
    return render_template('student-PersonalQs.html', form=form)

# route to get the form data from the cs quiz
@students_blueprint.route('/CSQs', methods = ['GET', 'POST'])
def CSQuestion():
    form = StudentCSQs(request.form)
    if request.method == 'POST' and form.validate():
        studentcsqs = CSQs()
        studentcsqs.userid = session['email']
        studentcsqs.studycs = form.StudyCSUni.data
        studentcsqs.thinkcs = form.ThinkOfCS.data
        studentcsqs.csinteresting = form.CSInteresting.data
        studentcsqs.csinterestingwhy = form.CSInterestingWhy.data
        studentcsqs.cschallenging = form.CSChallenging.data
        studentcsqs.cschallengingwhy = form.CSChallengingWhy.data
        studentcsqs.internetcentral = form.InternetCentral.data
        studentcsqs.wordexcelcentral = form.WordExcelCentral.data
        studentcsqs.installingcentral = form.InstallingCentral.data
        studentcsqs.programmingcentral = form.ProgrammingCentral.data
        studentcsqs.solvingproblemscentral = form.SolvingProblemsCentral.data
        studentcsqs.relatedtomaths = form.RelatedToMaths.data
        studentcsqs.workwithothers = form.WorkWithOthers.data
        studentcsqs.menmorelikely = form.MenMoreLikely.data
        studentcsqs.donenocomputer = form.DoneNoComputer.data
        studentcsqs.heardcompthinking = form.HeardOfCompThinking.data
        studentcsqs.compthinkingmeaning = form.CompThinkingMeaning.data
        studentcsqs.save()

        return redirect(url_for('bebras.bebrasquiz1'))

    elif request.method == 'POST' and form.validate() == False:
        if form.errors:
            errors = form.errors
            for i in errors:
                flash(i)

    return render_template('student-csqs.html', form=form)



@students_blueprint.route('/profile', methods=['GET', 'POST'])
def profile():
    if session.get('email'):
        user = User.objects().filter(email=session.get('email')).first()
        # find assignments
        # need to find the assignment which is open as well as same as the same school
        assignments = Assignment.objects(school=user.school.id)
        return render_template('student-profile.html', user=user, assignments=assignments)
    else:
        return redirect(url_for('login'))


# This method can only be accessed by a teacher
# this route is for loading the list of students for teacher to approve/disapprove
@students_blueprint.route('/', methods=['GET', 'POST'])
def student_list():
    if session.get('email'):
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            students = User.objects().filter(user_type='student')
            return render_template('students.html', students=students, user=user)
        else:
            return redirect(url_for('students.profile'))
    else:
        return redirect(url_for('login'))


# This method can only be accessed by a teacher
# Approve a new student
# when teacher clicks on green arrow to approve student this route is executed
@students_blueprint.route('/approve/<student_id>', methods=['GET', 'POST'])
def approve(student_id):
    if session.get('email'):
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get the student by student_id
            # update the approve value to true
            User.objects(id=student_id).update_one(approved=True)
            # Redirect to student list page
            return redirect(url_for('students.student_list'))
        else:
            return redirect(url_for('students.profile'))
    else:
        return redirect(url_for('login'))


# This method can only be accessed by a teacher
# Approve a new student
# when teacher clicks on red x to remove student this route is executed
@students_blueprint.route('/remove/<student_id>', methods=['GET', 'POST'])
def remove(student_id):
    if session.get('email'):
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get the student by student_id
            User.objects(id=student_id).delete()
            return redirect(url_for('students.student_list'))
        else:
            return redirect(url_for('students.profile'))
    else:
        return redirect(url_for('login'))

# this route is for the student progress page, when you click on a students name from the students list
@students_blueprint.route('/progress/<student_id>', methods=['GET', 'POST'])
def progress(student_id):
    if session.get('email'):
        # check if user is logged in
        teacher = User.objects().filter(email=session.get('email')).first()
        if teacher.user_type == 'instructor' or teacher.user_type == 'admin':
            student = User.objects(id=student_id).first()
            # get the students data
            teacher = User.objects().filter(email=session['email']).first()
            bebras1 = BebrasQuiz1.objects().filter(email=student.email).first() 
            # get bebras 1 quiz results 
            bebras2 = BebrasQuiz2.objects().filter(email=student.email).first()
            # get bebras 2 quiz results
            return render_template('student-progress.html', user=teacher, student=student, bebras1 = bebras1, bebras2 = bebras2)
        else:
            return redirect(url_for('students.profile'))
    else:
        return redirect(url_for('login'))

# this route for the edit profile page for students
@students_blueprint.route('/edit_profile', methods=['GET', 'POST'])
def edit_profile():
    if session.get('email'):
        form = EditForm()

cs2go/students/templates/students/student-create.html
{% extends "base.html" %}

{% block content %}
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a style="float: right;" class="navbar-brand" href="{{ url_for('login') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                    &nbsp;&nbsp;CS2Go
                  </a>
            </div>
        </div>
    </nav>
    <div id="backgroundRegisterPage" style="height: 580px;">
        <div class="container">
            <div id="signupbox" style="margin-top:25px;"
                 class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <form id="signupform" class="form-horizontal" role="form" method="POST"
                      action="{{ url_for('students.create') }}">
                {{ form.hidden_tag() }}
                    <div class="panel panel-info">
                        <!--This part will show the error messages-->
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-danger">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                        <div id="registerPage" class="panel-heading">
                            <div class="panel-title"><h2>Sign Up</h2>
                                <div class="progress" style="width: 60%; float: right; margin-top: -50px;">
                                    <div class="progress-bar" style="width: 20%">1/5</div>
                                </div>
                            </div>
                        </div>

                        <div style="padding-top:30px" class="panel-body">
                            <div style="display:none" id="signupalert" class="alert alert-danger col-sm-12">
                                <p>Error:</p>
                                <span></span>
                            </div>
                        </div>
                        <div style="margin-bottom:25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-education"></i></span>
                            {{ form.school(class='form-control') }}
                        </div>
                        <div id="new-school" style=" margin-bottom:25px" class="input-group hide-element">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-new-window"></i>
                            </span>
                            {{ form.school_name(class='form-control',placeholder='Please enter the name of your school') }}
                        </div>
                        <div style="margin-bottom:25px" class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-user"></i>
                            </span>
                            {{ form.name(class='form-control',placeholder='First Name') }}
                        </div>
                        <div style="margin-bottom:25px" class="input-group">
                        <span class="input-group-addon">
                            <i class="glyphicon glyphicon-user"></i>
                        </span>
                            {{ form.surname(class='form-control',placeholder='Last Name') }}
                        </div>

                        <div style="margin-bottom:25px" class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-envelope"></i>
                            </span>
                            {{ form.email(class='form-control', placeholder='Username or email') }}
                        </div>

                        <div style="margin-bottom:25px" class="input-group">
                        <span class="input-group-addon">
                            <i class="glyphicon glyphicon-lock"></i>
                        </span>
                            {{ form.password(class='form-control',placeholder='Password') }}
                        </div>
                        {{ form.submit(class='btn btn-primary btn-block') }}
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

cs2go/students/templates/students/student-edit-profile.html
{% extends "base.html" %}
{% block content %}

    <!-- Display below navbar if logged in user is a student -->
    {% if user.user_type=='student' %}
        <nav id="navbarColor" class="navbar navbar-inverse">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse-2"><span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                        <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                    &nbsp;&nbsp;CS2Go
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="navbar-collapse-2">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle"
                               href="#">{{ user.name }} {{ user.surname }} <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                    Profile</a></li>
                                <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                    out</a></li>
                            </ul>
                        </li>
                        <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                                class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    {% endif %}
    <!-- End navbar -->

    <div id="backgroundRegisterPage" style="height: 580px;">
        <div class="container">
            <div id="loginbox" style="margin-top:50px;"
                 class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

                <div class="panel panel-info">
                    <!--This part will show the error messages-->
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-success">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <div id="registerPage" class="panel-heading">
                        <div class="panel-title">
                            <h2>Update Profile</h2>
                        </div>
                    </div>
                    <div style="padding-top:30px" class="panel-body">
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12">
                        </div>
                        <form id="loginform" class="form-horizontal" role="form" method='post'
                              action="{{ url_for('students.edit_profile') }}">
                            {{ form.hidden_tag() }}
                            <div style="margin-bottom:25px" class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-user"></i>
                            </span>
                                {{ form.name(class='form-control', placeholder='First Name') }}
                            </div>
                            <div style="margin-bottom:25px" class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-lock"></i>
                            </span>
                                {{ form.surname(class='form-control', placeholder='Last Name') }}
                            </div>
                            {{ form.submit(class='btn btn-primary btn-block') }}
                        </form>
                    </div>

                    <div class="form-group" style="background-color: white">
                        <div class="col-md-12 control" style="background-color: white; border-radius: 5px;">
                            <div style="border-top: 0.5px solid#888; padding-top:15px; font-size:85%">
                                Don't have an account!
                                <a href="{{ url_for('teachers.create') }}">Sign up here</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

cs2go/students/templates/students/students.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {#Show the Home Page#}
                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>

            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li>
                        <a data-toggle="tooltip" title="View all files" href="{{ url_for('files.file_list') }}">
                            <span class="glyphicon glyphicon-file"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tooltip" title="View students" href="{{ url_for('students.student_list') }}">
                            <span class="glyphicon glyphicon-list" data-toggle="tooltip"
                                  data-original-title="Users"></span>
                        </a>
                    </li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            {{ user.name }} {{ user.surname }}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li>
                                <a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>Files</a>
                            </li>
                            <li>
                                <a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i>
                                    Log out
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method="post" action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        <div class="d-inline-flex">
            <h3>Students</h3>
            <table id="content" class="table table-hover table-responsive">
                <thead>
                <tr>
                    <th>School</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Username</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% if students %}
                    {% for student in students %}
                        {#Check the loop by index#}
                        {% if loop.index % 2 == 0 %}
                            <tr style="background-color: rgb(213,206,218);cursor: pointer;"
                                onclick="document.location = '/students/progress/{{ student.id }}';">
                                <td>{{ student.school.name }}</td>
                                <td>{{ student.name }}</td>
                                <td>{{ student.surname }}</td>
                                <td>{{ student.email }}</td>
                                <td>
                                    {#Show the approve icon only if the student is not approved#}
                                    {% if not student.approved %}
                                        <a data-toggle="tooltip" title="Approve Student"
                                           href="{{ url_for('students.approve',student_id=student.id) }}">
                                            <span style="color: #00ff00;" class="glyphicon glyphicon-ok"></span>
                                        </a>
                                    {% endif %}
                                    <a data-toggle="tooltip" title="Delete Student"
                                       href="{{ url_for('students.remove',student_id=student.id) }}">
                                        <span style="color: #ec405c;" class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr style="cursor: pointer;background-color: rgb(245,240,240)"
                                onclick="document.location = '/students/progress/{{ student.id }}';">
                                <td>{{ student.school.name }}</td>
                                <td>{{ student.name }}</td>
                                <td>{{ student.surname }}</td>
                                <td>{{ student.email }}</td>
                                <td>
                                    {#show the approve icon only if the student is not approved#}
                                    {% if not student.approved %}
                                        <a data-toggle="tooltip" title="Approve Student"
                                           href="{{ url_for('students.approve',student_id=student.id) }}">
                                            <span style="color: #00ff00;" class="glyphicon glyphicon-ok"></span>
                                        </a>
                                    {% endif %}
                                    <a data-toggle="tooltip" title="Delete Student"
                                       href="{{ url_for('students.remove',student_id=student.id) }}">
                                        <span style="color: #ec405c;" class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <div id="pagination"></div>
        </div>
    </div>
{% endblock %}