cs2go/assignments/views.py
import os
from flask import Blueprint, render_template, request, session, redirect, url_for, send_from_directory
from werkzeug.utils import secure_filename
from cs2go import app

from cs2go.assignments.forms import AssignmentForm, AssignmentDocumentForm
from cs2go.models import User, Assignment, School, Document

assignments_blueprint = Blueprint('assignments',
                                  __name__,
                                  template_folder='templates/assignments')
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'pptx', 'docx', 'mp4'}


# Only instructor and admin can access this route
@assignments_blueprint.route('/', methods=['GET', 'POST'])
def assignment_list():
    if session.get('email'):
        # get the logged in user by session.get('email')
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            assignments = Assignment.objects(school=user.school.id)
            # get all the assignments from the Assignments collection
        else:
            return redirect(url_for('students.profile'))
            #if logged in user is not either teacher or admin redirect to student homepage
        return render_template('assignments.html', assignments=assignments, user=user)
    else:
        return redirect(url_for('login'))


# Only instructor and admin can access this route
@assignments_blueprint.route('/details/<assignment_id>', methods=['GET', 'POST'])
def assignment_details(assignment_id):
    if session.get('email'):
        # get the logged in user by session.get('email')
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get all the question from the Post table
            assignment = Assignment.objects(id=assignment_id).first()
        else:
            return redirect(url_for('students.profile'))
        return render_template('assignment-details.html', assignment=assignment, user=user)
    else:
        return redirect(url_for('login'))


# Only instructor and admin can access this route
@assignments_blueprint.route('/create', methods=['GET', 'POST'])
def create_assignment():
    # get the logged in user by session.get('email')
    if session.get('email'):
        # get instance of assignment form
        form = AssignmentForm(request.form)
        user = User.objects().filter(email=session.get('email')).first()
        # get the user document from database from logged in user
        if user.user_type == 'instructor' or user.user_type == 'admin':
            if request.method == 'POST' and form.validate():
                # check if the user type is teacher or admin and validate form for incoming POST request
                # First save the Question
                assignment = Assignment()
                # declare instance of assignment model for use and assign form data to it
                assignment.title = form.title.data
                assignment.description = form.description.data
                assignment.submission_date = form.submission_date.data
                assignment.created_by = user.id
                assignment.school = user.school.id
                assignment.save()
                # save the assignment to the database
                # get the user school
                user_school = School.objects(id=user.school.id).first()
                # get the school document from database based on the school id
                user_school.assignments.append(assignment.id)
                # add the assignment to the list of assignments for the school
                user_school.save()
                # redirect the user in the assignments list route
                return redirect(url_for('assignments.assignment_list'))
        else:
            return redirect(url_for('students.profile'))
        return render_template('assignment-create.html', form=form, user=user)
    else:
        return redirect(url_for('login'))


# only student can access this route
# for student uploading documents
@assignments_blueprint.route('/document/<assignment_id>', methods=['GET', 'POST'])
def upload_document(assignment_id):
    # get the logged in user by session.get('email')
    if session.get('email'):
        submitted = False
        assignment = Assignment.objects(id=assignment_id).first()
        # check if the user has already submitted the assignment or not
        form = AssignmentDocumentForm()
        # create instance of AssignmentDocumentForm
        user = User.objects().filter(email=session.get('email')).first()
        #get user document of logged in user by email of user in session
        previously_submitted_doc = Document.objects(assignment=assignment.id, submitted_by=user.id).first()
        #check if the user has already submitted a document for this assignment
        if previously_submitted_doc is not None:
            # if user has already submitted document for assignment
            submitted = True
            form.submit.label.text = 'Edit Upload'
        if request.method == 'POST' and form.validate():
            file = form.file.data
            if file and allowed_file(file.filename):
                # check if the file submitted in the POST request is of the allowed type, check by extension
                if not submitted:
                    filename = secure_filename(file.filename)
                    # get name of the file
                    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
                    # save the file name in the database
                    document = Document()
                    # declare instance of Document model and assign form data to it
                    document.filename = filename
                    document.assignment = assignment.id
                    document.submitted_by = user.id
                    document.save()
                    assignment.documents.append(document.id)
                    assignment.save()
                    # set a flash message that document successfully updated
                else:
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
                    previously_submitted_doc.filename = filename
                    previously_submitted_doc.save()
                    # set a flash message that document successfully updated
            # redirect the user in the questions routes
            return redirect(url_for('assignments.assignment_list'))
        return render_template('assignment-document.html', form=form, assignment=assignment, user=user,
                               submitted=submitted, document=previously_submitted_doc)
    else:
        return redirect(url_for('login'))


@assignments_blueprint.route('/close/<assignment_id>', methods=['GET', 'POST'])
def close_assignment(assignment_id):
    if session.get('email'):
        # get the logged in user by session.get('email')
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # check the user type
            assignment = Assignment.objects(id=assignment_id).first()
            # get document from assignment collection based on the id
            # make the assignment status false
            assignment.status = False
            assignment.save()
            # update the status of the assignment to false, meaning it is closed and no longer accepting submissions
        return redirect(url_for('assignments.assignment_details', assignment_id=assignment_id))

    else:
        return redirect(url_for('login'))


@assignments_blueprint.route('/open/<assignment_id>', methods=['GET', 'POST'])
def open_assignment(assignment_id):
    if session.get('email'):
        # get the logged in user by session.get('email')
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            # get the document from assignment collection in database based on assignment id
            assignment = Assignment.objects(id=assignment_id).first()
            # make the assignment status True
            assignment.status = True
            assignment.save()
            # update the status to open, now accepting submissions again
        return redirect(url_for('assignments.assignment_details', assignment_id=assignment_id))
    else:
        return redirect(url_for('login'))


# Checking if the file uploaded is in the allowed extension 
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

#route for downloading assignments
@assignments_blueprint.route('/download/<file_name>', methods=['GET', 'POST'])
def download(file_name):
    uploads = app.config['UPLOAD_FOLDER']
    return send_from_directory(directory=uploads, filename=file_name)

cs2go/assignments/templates/assignments/assignment-create.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>

            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li><a data-toggle="tooltip" title="View all files" href="{{ url_for('files.file_list') }}"><span
                            class="glyphicon glyphicon-file"></span></a></li>
                    <li><a data-toggle="tooltip" title="View students"
                           href="{{ url_for('students.student_list') }}"><span
                            class="glyphicon glyphicon-list" data-toggle="tooltip"
                            data-original-title="Users"></span></a></li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">{{ user.name }} {{ user.surname }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li><a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>
                                Files</a></li>
                            <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                out</a></li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method="post" action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        <div style="background-color: #D8BFD8;padding: 10px;border-radius: 5px">
            <a href="{{ url_for('assignments.assignment_list') }}">
                <span><i class="fa fa-long-arrow-left" aria-hidden="true" style="font-size: 18px;"></i></span>
                <span style="margin-left: 5px">Back to assignments</span>
            </a>
        </div>
        <div>
            <h4 style="margin: 24px 0">Create New Assignment</h4>
        </div>
        <form action="{{ url_for('assignments.create_assignment') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-inline">
                <label>Title:</label>
                {{ form.title(class='form-control',style='width:100%',placeholder="Title") }}
            </div>
            <div style="margin-top: 40px">
                <label>Submission Date</label>
                {{ form.submission_date(class='form-control',id='datepicker') }}
            </div>
            <div>
                <h4 style="margin-top: 40px">Description:</h4>
                {{ form.description(class='form-control') }}
            </div>
            {{ form.submit(class="btn btn-info",style="float: right; padding: 6px 16px; background-color: #D8BFD8; border:
        #D8BFD8; color: black; font-weight: bold; margin-top: 24px") }}
        </form>
    </div>

{% endblock %}

cs2go/assignments/templates/assignments/assignment-details.html
{% extends "base.html" %}
{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>

    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li><a data-toggle="tooltip" title="View all files"
                           href="{{ url_for('files.file_list') }}"><span
                            class="glyphicon glyphicon-file"></span></a></li>
                    <li><a data-toggle="tooltip" title="View students"
                           href="{{ url_for('students.student_list') }}"><span
                            class="glyphicon glyphicon-list" data-toggle="tooltip"
                            data-original-title="Users"></span></a></li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle"
                           href="#">{{ user.name }} {{ user.surname }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li><a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>
                                Files</a></li>
                            <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                out</a></li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method='post' action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>


    <!-- Display files related to lesson-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div style="background-color: #D8BFD8;padding: 10px;border-radius: 5px">
                    <a href="{{ url_for('assignments.assignment_list') }}">
                        <span><i class="fa fa-long-arrow-left" aria-hidden="true" style="font-size: 18px;"></i></span>
                        <span style="margin-left: 5px">Back to assignments</span>
                    </a>
                </div>
                {#Display the Assignment Details here#}
                <div class="jumbotron">
                    <h3 class="text-center">Assignment Details</h3>
                    {# Assignment Title #}
                    <div class="row">
                        <div class="col-lg-3"><strong>Title</strong></div>
                        <div class="col-lg-6">{{ assignment.title }}</div>
                    </div>
                    <hr>
                    {# Assignment Description #}
                    <div class="row">
                        <div class="col-lg-3"><strong>Description</strong></div>
                        <div class="col-lg-6">{{ assignment.description | safe }}</div>
                    </div>
                    <hr>
                    {# Assignment Creator #}
                    <div class="row">
                        <div class="col-lg-3"><strong>Created By</strong></div>
                        <div class="col-lg-6">{{ assignment.created_by.name }}</div>
                    </div>
                    <hr>
                    {# Assignment Submission Date #}
                    <div class="row">
                        <div class="col-lg-3"><strong>Submission Date</strong></div>
                        <div class="col-lg-6">{{ assignment.submission_date.strftime('%Y-%m-%d') }} </div>
                    </div>
                    {# Assignment Status #}
                    <hr>
                    <div class="row">
                        <div class="col-lg-3"><strong>Status</strong></div>
                        <div class="col-lg-6">
                            {% if assignment.status %}
                                Open
                            {% else %}
                                Close
                            {% endif %}
                        </div>
                    </div>
                    <hr>
                    <div class="text-center">
                        {% if assignment.status %}
                            {#Button for close this assignment#}
                            <a href="{{ url_for('assignments.close_assignment',assignment_id=assignment.id) }}"
                               class="btn btn-danger">Close Assignment</a>
                        {% else %}
                            {#Button for open this assignment#}
                            <a href="{{ url_for('assignments.open_assignment',assignment_id=assignment.id) }}"
                               class="btn btn-primary">Open Assignment</a>
                        {% endif %}
                    </div>
                </div>
                <div class="jumbotron">
                    <h3 class="text-center">Assignment Documents</h3>
                    {# Display the Assignment Document #}
                    <table id="mytab1" class="table table-hover table-responsive">
                        <thead>
                        <tr>
                            <th>File Name</th>
                            <th class="text-center">Submitted By</th>
                            <th style="text-align: right">Submission Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if assignment %}
                            {% for document in assignment.documents %}
                                {#Check the loop by index#}
                                {% if loop.index % 2 == 0 %}
                                    <tr style="background-color: rgb(213,206,218)">
                                        <td style="vertical-align: middle"><a
                                                href="{{ url_for('assignments.download',file_name=document.filename) }}">{{ document.filename }}</a>
                                        </td>
                                        <td align="center" style="vertical-align: middle">
                                            <p>{{ document.submitted_by.name }}</p>
                                        </td>
                                        <td align="right">{{ document.submitted_date.strftime('%Y-%m-%d') }}</td>
                                    </tr>
                                {% else %}
                                    <tr style="background-color: rgb(245,240,240)">
                                        <td style="vertical-align: middle">
                                            <a href="{{ url_for('assignments.download',file_name=document.filename) }}">{{ document.filename }}</a>
                                        </td>
                                        <td align="center" style="vertical-align: middle">
                                            <p>{{ document.submitted_by.name }}</p>
                                        </td>
                                        <td align="right">{{ document.submitted_date.strftime('%Y-%m-%d') }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                    <div id="pagination"></div>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

cs2go/assignments/templates/assignments/assignment-document.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a student -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2"><span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('students.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">{{ user.name }} {{ user.surname }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i>Log out</a>
                            </li>
                        </ul>
                    </li>
                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    {% if user.approved %}
                        <form class="navbar-form" role="form" method=POST action="{{ url_for('students.profile') }}">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" id="searchBar"
                                       placeholder="Search Files">

                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i
                                            class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        {#Display the Assignment Details here#}
        <div class="jumbotron">
            <h3 class="text-center">Assignment Details</h3>
            {# Assignment Title #}
            <div class="row">
                <div class="col-lg-3"><strong>Title</strong></div>
                <div class="col-lg-6">{{ assignment.title }}</div>
            </div>
            <hr>
            {# Assignment Description #}
            <div class="row">
                <div class="col-lg-3"><strong>Description</strong></div>
                <div class="col-lg-6">{{ assignment.description | safe }}</div>
            </div>
            <hr>
            {# Assignment Creator #}
            <div class="row">
                <div class="col-lg-3"><strong>Created By</strong></div>
                <div class="col-lg-6">{{ assignment.created_by.name }}</div>
            </div>
            <hr>
            {# Assignment Submission Date #}
            <div class="row">
                <div class="col-lg-3"><strong>Submission Date</strong></div>
                <div class="col-lg-6">{{ assignment.submission_date.strftime('%Y-%m-%d') }} </div>
            </div>
            {# Assignment Status #}
            <hr>
            <div class="row">
                <div class="col-lg-3"><strong>Status</strong></div>
                <div class="col-lg-6">
                    {% if assignment.status %}
                        Open
                    {% else %}
                        Close
                    {% endif %}
                </div>
            </div>
        </div>
        {% if assignment.status %}
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Upload Files</strong></div>

                <div class="panel-body">
                    <h4>Select files from your computer</h4>

                    <form action="{{ url_for('assignments.upload_document',assignment_id=assignment.id) }}"
                          method="post"
                          enctype="multipart/form-data">
                        <!--CSRF TOKEN THIS IS FOR SECURITY-->
                        {{ form.hidden_tag() }}
                        {# If previously submitted document then display that file download link here#}
                        {% if document is not none %}
                            <div style="margin-bottom: 10px">
                                <a href="{{ url_for('assignments.download',file_name=document.filename) }}">{{ document.filename }}</a>

                            </div>
                        {% endif %}
                        {{ form.file }}<br>
                        {# If previously updated document then change the label of submit button to edit upload #}
                        {{ form.submit(class='btn btn-sm btn-primary') }}
                    </form>
                    <br>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}