cs2go/files/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, send_from_directory
from werkzeug.utils import secure_filename
from cs2go.models import User, File, School, Module1, Module2, Module3
from cs2go import app
import sys

from cs2go.files.forms import UploadForm, TagForm
import os

files_blueprint = Blueprint('files',
                            __name__,
                            template_folder='templates/files')

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'pptx', 'docx', 'mp4'}


@files_blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
    #check if the user is logged in by checking session.email
    if session.get('email'):
        form = UploadForm()
        #create instacnce of UploadForm
        user = User.objects().filter(email=session.get('email')).first()
        #get the user document from database based on the email of the logged in user
        if request.method == 'POST':
            file = form.file.data
            if file and allowed_file(file.filename):
                #check if file has been selected for upload and check if it is the allowed type
                filename = secure_filename(file.filename)
                #convert the file name into a 'secure version' so it can be stored in database
                #https://werkzeug.palletsprojects.com/en/0.15.x/utils/
                file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
                print('Hello world!', file=sys.stderr)
                # save the file name in the database
                new_file = File()
                #declare instance of File model and assign data
                new_file.filename = filename
                new_file.user = user.id
                new_file.save()
                #save the uploaded fle to database and store it in the uploads folder
                return redirect(url_for('files.file_list'))
        return render_template('upload-file.html', form=form, user=user)
    else:
        return redirect(url_for('login'))

#route for downloading file
@files_blueprint.route('/download/<file_id>', methods=['GET', 'POST'])
def download(file_id):
    if session.get('email'):
        file = File.objects(id=file_id).first()
        # get file details from File collection
        if file:
            # if the file exists 
            uploads = app.config['UPLOAD_FOLDER']
            # set uploads to the directory of the uploads folder
            return send_from_directory(directory=uploads, filename=file.filename)
            #download the file
    else:
        return redirect(url_for('login'))


@files_blueprint.route('/', methods=['GET', 'POST'])
def file_list():
    # get the logged in user by session.get('email')
    if session.get('email'):
        user = User.objects().filter(email=session.get('email')).first()
        #get the user document from database based on the email of the logged in user
        files = File.objects()
        return render_template('files.html', files=files, user=user)
    else:
        return redirect(url_for('login'))


@files_blueprint.route('/add_to_module1/<file_id>', methods=['GET', 'POST'])
def add_to_module1(file_id):
    # Check if the user is logged in or not. if not logged in then redirect to login
    if session.get('email'):
        file = File.objects(id=file_id).first()
        # get the logged in user school
        # add the file to the module1 array
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            user_school = School.objects(id=user.school.id).first()
            #get the school document from School collection that the student is enrolled
            user_school_module1 = Module1.objects(id=user_school.module1.id).first()
            user_school_module1.files.append(file.id)
            user_school_module1.save()
            return redirect(url_for('files.file_list'))
    else:
        return redirect(url_for('login'))


@files_blueprint.route('/add_to_module2/<file_id>', methods=['GET', 'POST'])
def add_to_module2(file_id):
    # Check if the user is logged in or not. if not logged in then redirect to login
    if session.get('email'):
        file = File.objects(id=file_id).first()
        # get the logged in user school
        # add the file to the module2 array
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            user_school = School.objects(id=user.school.id).first()
            user_school_module2 = Module2.objects(id=user_school.module2.id).first()
            user_school_module2.files.append(file.id)
            user_school_module2.save()
            return redirect(url_for('files.file_list'))
    else:
        return redirect(url_for('login'))


@files_blueprint.route('/add_to_module3/<file_id>', methods=['GET', 'POST'])
def add_to_module3(file_id):
    # Check if the user is logged in or not. if not logged in then redirect to login
    if session.get('email'):
        file = File.objects(id=file_id).first()
        # get the logged in user school
        # add the file to the module3 array
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.user_type == 'admin':
            user_school = School.objects(id=user.school.id).first()
            user_school_module3 = Module3.objects(id=user_school.module3.id).first()
            user_school_module3.files.append(file.id)
            user_school_module3.save()
            return redirect(url_for('files.file_list'))
    else:
        return redirect(url_for('login'))


# Checking if the file uploaded is in the allowed extension variable
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@files_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    if session.get('email'):
        search_tag = request.form.get('search')
        user = User.objects().filter(email=session.get('email')).first()
        # check if the user is teacher or if student then also check if the student is approved or not
        if (user.user_type == 'instructor' or user.approved) or user.user_type == 'admin':
            files = File.objects()
            # Now check for each files in which file this tag exists
            tagged_files = list()
            for file in files:
                # Loop through the tag and match the file tag with the search tag
                for file_tag in file.tags:
                    if file_tag.upper() == search_tag.upper():
                        tagged_files.append(file)
                        break
            #Also loop through all the names of the files to see if the search matches
            for file in files:
                if search_tag.upper() in file.filename.upper():
                    tagged_files.append(file)
                    

            return render_template('search-module.html', files=tagged_files, user=user)
    else:
        return redirect(url_for('login'))

# route for file details
@files_blueprint.route('/details/<file_id>', methods=['GET', 'POST'])
def details(file_id):
    if session.get('email'):
        form = TagForm()
        user = User.objects().filter(email=session.get('email')).first()
        if user.user_type == 'instructor' or user.approved or user.user_type == 'admin':
            file = File.objects(id=file_id).first()
            return render_template('file-details.html', file=file, user=user, form=form)
    else:
        return redirect(url_for('login'))

# route for adding tags to a file
@files_blueprint.route('/add_tag/<file_id>', methods=['GET', 'POST'])
def add_tag(file_id):
    if session.get('email'):
        # check if the user is logged in
        new_tags = request.form.get('tags').split(',')
        # get the tags from the form data and split up accordingly
        user = User.objects().filter(email=session.get('email')).first()
        # get user data for logged in user
        if user.user_type == 'instructor' or user.approved or user.user_type == 'admin':
            file = File.objects(id=file_id).first()
            # get file data by file id
            tag_list = list()
            for tag in file.tags:
                tag_list.append(tag.upper())
            for tag in new_tags:
                if tag.strip().upper() not in tag_list:
                    # trim the tag. so that no empty space before the tag and also after the tag
                    tag_list.append(tag.strip().upper())
            file.tags = tag_list
            file.save()
            # save the file with its new tags
        return redirect(url_for('files.file_list'))
    else:
        return redirect(url_for('login'))

cs2go/files/templates/files/file-details.html
{% extends "base.html" %}
{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>

    <!-- Display below navbar if logged in user is a teacher -->
    {% if user.user_type=='instructor' %}
        <nav id="navbarColor" class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                        <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                    &nbsp;&nbsp;CS2Go
                    </a>

                </div>

                <div class="collapse navbar-collapse" id="navbar-collapse-2">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{{ url_for('forums.questions') }}">
                                <span class="glyphicon glyphicon-comment"></span>
                            </a>
                        </li>

                        <li><a data-toggle="tooltip" title="View all files"
                               href="{{ url_for('files.file_list') }}"><span
                                class="glyphicon glyphicon-file"></span></a></li>
                        <li><a data-toggle="tooltip" title="View students"
                               href="{{ url_for('students.student_list') }}"><span
                                class="glyphicon glyphicon-list" data-toggle="tooltip"
                                data-original-title="Users"></span></a></li>

                        <li id="dropdown1" class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle"
                               href="#">{{ user.name }} {{ user.surname }} <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                    Profile</a></li>
                                <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                    Upload Files</a>
                                </li>
                                <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                        class="glyphicon glyphicon-list"></i> Assignments</a>
                                </li>
                                <li><a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>
                                    Files</a></li>
                                <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                    out</a></li>
                            </ul>
                        </li>

                        <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                                class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>

                    <div class="col-sm-3 col-md-3" style="float: right;">
                        <form class="navbar-form" role="form" method='post' action="{{ url_for('files.search') }}">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" id="searchBar"
                                       placeholder="Search Files">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i
                                            class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    {% endif %}
    <!-- End of teacher navbar -->

    <!-- Display below navbar if logged in user is a student -->
    {% if user.user_type=='student' %}
        <nav id="navbarColor" class="navbar navbar-inverse">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse-2"><span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                        <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                    &nbsp;&nbsp;CS2Go
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="navbar-collapse-2">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle"
                               href="#">{{ user.name }} {{ user.surname }} <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                    Profile</a></li>
                                <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                    out</a></li>
                            </ul>
                        </li>
                        <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                                class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>

                    <div class="col-sm-3 col-md-3" style="float: right;">

                        <form class="navbar-form" role="form" method='post' action="{{ url_for('students.profile') }}">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" id="searchBar"
                                       placeholder="Search Files">

                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i
                                            class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    {% endif %}
    <!-- End navbar -->

    <!-- Display files related to lesson-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="jumbotron">
                    <table id="mytab1" class="table table-hover table-responsive">
                        <tr style="pointer-events: none;">
                            <th>File Details</th>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file"></span>
                                <a id="abc" target="_blank"
                                   href="{{ url_for('schools.download',file_name=file.filename) }}">
                                    <h5 style="display: inline;"> {{ file.filename }}</h5></a><br><br>
                                <span>Tags :</span>
                                {% for tag in file.tags %}
                                    <span style="border: 1px solid #666666;padding:5px;margin: 10px">{{ tag }}</span>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <form action="{{ url_for('files.add_tag', file_id=file.id) }}" method="post"
                                      enctype="multipart/form-data">
                                    <!--CSRF TOKEN THIS IS FOR SECURITY-->
                                    {{ form.hidden_tag() }}
                                    <p><strong>For Multiple Tags Separate with comma </strong></p>
                                    {{ form.tags(placeholder='Tags',class='form-control',style='max-width:250px;display:inline-block') }}
                                    {{ form.submit(class='btn btn-sm btn-primary') }}
                                </form>
                            </td>
                        </tr>

                    </table>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

cs2go/files/templates/files/files.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        body {
            background-color: #dbd8d9;
        }
    </style>
    <!-- Display below navbar if logged in user is a teacher -->
    <nav id="navbarColor" class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a style="float: right;" class="navbar-brand" href="{{ url_for('teachers.profile') }}">
                    <img src="/static/img/cs2GoIcon.png" style="width: 17.5%; float: left;">
                &nbsp;&nbsp;CS2Go
                </a>

            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('forums.questions') }}">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </li>

                    <li><a data-toggle="tooltip" title="View all files" href="{{ url_for('files.file_list') }}"><span
                            class="glyphicon glyphicon-file"></span></a></li>
                    <li><a data-toggle="tooltip" title="View students"
                           href="{{ url_for('students.student_list') }}"><span
                            class="glyphicon glyphicon-list" data-toggle="tooltip"
                            data-original-title="Users"></span></a></li>

                    <li id="dropdown1" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">{{ user.name }} {{ user.surname }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('profile_edit') }}"><i class="glyphicon glyphicon-cog"></i> Edit
                                Profile</a></li>
                            <li><a href="{{ url_for('files.upload') }}"><i class="glyphicon glyphicon-upload"></i>
                                Upload Files</a>
                            </li>
                            <li><a href="{{ url_for('assignments.assignment_list') }}"><i
                                    class="glyphicon glyphicon-list"></i> Assignments</a>
                            </li>
                            <li><a href="{{ url_for('files.file_list') }}"><i class="glyphicon glyphicon-file"></i>
                                Files</a></li>
                            <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log
                                out</a></li>
                        </ul>
                    </li>

                    <li><a data-toggle="tooltip" title="Log out" href="{{ url_for('logout') }}"><i
                            class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

                <div class="col-sm-3 col-md-3" style="float: right;">
                    <form class="navbar-form" role="form" method='post' action="{{ url_for('files.search') }}">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" id="searchBar"
                                   placeholder="Search Files">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i
                                        class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <!-- End navbar -->

    <div class="container">
        <div class="d-inline-flex">
            <a href="{{ url_for('files.upload') }}" class="btn btn-info"
               style="margin: 28px 28px 16px 0px; background-color: #D8BFD8; border-color: #D8BFD8; color: black; font-weight: bold">
                Add New File
            </a>
            <table id="content" class="table table-hover table-responsive">
                <thead>
                <tr>
                    <th>File</th>
                    <th>Tags</th>
                    <th>Download</th>
                    <th>Add</th>
                </tr>
                </thead>
                <tbody>
                {% if files %}
                    {% for file in files %}
                        {#Check the loop by index#}
                        {% if loop.index % 2 == 0 %}
                            <tr>
                                <td><a href="{{ url_for('files.details',file_id=file.id) }}">{{ file.filename }}</a>
                                </td>
                                <td style="width: 50%">
                                    {% for tag in file.tags %}
                                        <span style="border: 1px solid #666666;padding:2px;margin: 2px">{{ tag }}</span>
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{{ url_for('files.download',file_id=file.id) }}" data-toggle="tooltip"
                                       title="Click to download"
                                       class="btn btn-primary" download>
                                        <span style="font-size: 14px;" class="glyphicon glyphicon-download"></span>
                                    </a>
                                </td>
                                <td>
                                    <li style="list-style-type: none;" class="dropdown">
                                        <a data-toggle="dropdown" class="dropdown-toggle" href="">
                                        <span style="color: black; padding-top: 8px;"
                                              class="glyphicon glyphicon-option-vertical"></span>
                                            <b class="caret"></b>
                                        </a>
                                        <ul style="margin-left: -50px;" class="dropdown-menu">
                                            <li style="text-align: center; border-bottom: 1px solid;"><a href=""></a><b>
                                                Add files to lesson</b></li>
                                            <li><a href="{{ url_for('schools.add_to_module1',file_id=file.id) }}"><i
                                                    class="glyphicon glyphicon-file"></i> Module1</a></li>
                                            <li><a href="{{ url_for('schools.add_to_module2',file_id=file.id) }}"><i
                                                    class="glyphicon glyphicon-file"></i> Module2</a></li>
                                            <li><a href="{{ url_for('schools.add_to_module3',file_id=file.id) }}"><i
                                                    class="glyphicon glyphicon-file"></i> Module3</a></li>
                                        </ul>
                                    </li>
                                </td>
                            </tr>
                        {% else %}
                            <tr class="active">
                                <td><a href="{{ url_for('files.details',file_id=file.id) }}">{{ file.filename }}</a>
                                </td>
                                <td style="width: 50%">
                                    {% for tag in file.tags %}
                                        <span style="border: 1px solid #666666;padding:2px;margin: 2px">{{ tag }}</span>
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{{ url_for('files.download',file_id=file.id) }}" data-toggle="tooltip"
                                       title="Click to download"
                                       class="btn btn-primary" download>
                                        <span style="font-size: 14px;" class="glyphicon glyphicon-download"></span>
                                    </a>
                                </td>
                                <td>
                                    <li style="list-style-type: none;" class="dropdown">
                                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                        <span style="color: black; padding-top: 8px;"
                                              class="glyphicon glyphicon-option-vertical"></span>
                                            <b class="caret"></b>
                                        </a>
                                        <ul style="margin-left: -50px;" class="dropdown-menu">
                                            <li style="text-align: center; border-bottom: 1px solid;">
                                                <a href=""></a>
                                                <b>Add files to lesson</b>
                                            </li>
                                            <li><a href="{{ url_for('schools.add_to_module1',file_id=file.id) }}"><i
                                                    class="glyphicon glyphicon-file"></i> Module1</a></li>
                                            <li><a href="{{ url_for('schools.add_to_module2',file_id=file.id) }}"><i
                                                    class="glyphicon glyphicon-file"></i> Module2</a></li>
                                            <li><a href="{{ url_for('schools.add_to_module3',file_id=file.id) }}"><i
                                                    class="glyphicon glyphicon-file"></i> Module3</a></li>
                                        </ul>
                                    </li>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <div id="pagination"></div>
        </div>
    </div>
{% endblock %}